# Generated by Django 5.1.4 on 2024-12-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_transaction_receiver_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver_account',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
