# Generated by Django 5.1.4 on 2024-12-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver_account',
            field=models.TextField(),
        ),
    ]
