# Generated by Django 5.1.4 on 2024-12-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_transaction_receiver_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='balance',
            field=models.TextField(),
        ),
    ]
